export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as TrendingIconList } from './TrendingIconList'
export { default as LimitedOfferBanner } from './LimitedOfferBanner'
export { default as SingleProductItem } from './SingleProductItem'
export { default as SectionHeading } from './SectionHeading'
export { default as LandingTopBanner } from './LandingTopBanner'
